# -*- coding: utf-8 -*-
"""TFM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Ucv0sVMCsHOUm2rdI0v40iOiiM4pSS8
"""

!pip install pydub

!pip install speechrecognition

!ffmpeg -i Grabación.mp3 Grabación.wav

import speech_recognition as sr

def transcribe_first_60_seconds(audio_file):
    recognizer = sr.Recognizer()

    with sr.AudioFile(audio_file) as source:
        audio_text = recognizer.record(source, duration=60)

    try:
        result = recognizer.recognize_google(audio_text, language="es")
        print(result)
    except sr.UnknownValueError:
        print("No se pudo transcribir el audio.")
    except sr.RequestError as e:
        print(f"Error en la solicitud: {e}")


audio_file_path = "Grabación.wav"
transcribe_first_60_seconds(audio_file_path)

import speech_recognition as sr
from moviepy.video.io.ffmpeg_tools import ffmpeg_extract_subclip

def transcribe_audio_in_segments(audio_file, segment_duration=60):
    recognizer = sr.Recognizer()

    with sr.AudioFile(audio_file) as source:
        total_duration = source.DURATION

    full_transcription = ""

    for start_time in range(0, int(total_duration), segment_duration):
        end_time = min(start_time + segment_duration, total_duration)

        output_file_path = f"Segmento_{start_time}_{end_time}.wav"
        ffmpeg_extract_subclip(audio_file, start_time, end_time, targetname=output_file_path)

        with sr.AudioFile(output_file_path) as segment_source:
            segment_text = recognizer.record(segment_source, duration=segment_duration)

        try:
            segment_transcription = recognizer.recognize_google(segment_text, language="es")
            full_transcription += segment_transcription + " "
        except sr.UnknownValueError:
            pass

    return full_transcription

audio_file_path = "Grabación.wav"
result = transcribe_audio_in_segments(audio_file_path)
print("Transcripción completa:")
print(result)

result

"""Analizar texto***********"""